/**
 * Everything the app does with houses. Screens call these; they never build
 * queries themselves, so the RLS-shaped gotchas below live in one place.
 *
 * Errors come back as plain `Error`s with messages meant for a person to read -
 * Postgres codes are translated here rather than in the UI.
 */
import type { PostgrestError } from '@supabase/supabase-js';

import { CHECK_VIOLATION, isPostgrestError, UNIQUE_VIOLATION } from '@/lib/postgrest';
import { supabase } from '@/lib/supabase';

export type House = {
  id: string;
  name: string;
  join_code: string;
  owner_id: string;
};

const HOUSE_COLUMNS = 'id, name, join_code, owner_id';

/**
 * Houses the signed-in user belongs to, most recently joined first.
 *
 * The `user_id` filter is load-bearing. The `memberships` SELECT policy is
 * `is_house_member(house_id)` - it returns every membership row of every house you
 * belong to, including your housemates'. Without the filter a three-player house
 * would come back three times.
 */
export async function listHouses(userId: string): Promise<House[]> {
  const { data, error } = await supabase
    .from('memberships')
    .select(`created_at, house:houses!inner(${HOUSE_COLUMNS})`)
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .returns<{ created_at: string; house: House }[]>();

  if (error) {
    throw new Error(`Could not load your houses. ${error.message}`);
  }

  return (data ?? []).map((row) => row.house);
}

/** One house by id. RLS returns nothing unless the caller is a member. */
export async function getHouse(houseId: string): Promise<House | null> {
  const { data, error } = await supabase
    .from('houses')
    .select(HOUSE_COLUMNS)
    .eq('id', houseId)
    .maybeSingle<House>();

  if (error) {
    throw new Error(`Could not load that house. ${error.message}`);
  }

  return data;
}

/**
 * Create a house and enrol the owner in it.
 *
 * Two statements, because the schema has no `create_house` RPC and adding one
 * would be a schema change. They are not atomic: if the membership insert fails
 * the house is deleted again, otherwise it would sit there holding its unique name
 * while never appearing in anyone's list.
 *
 * `join_code` is generated by the database (`generate_join_code()`), so it is read
 * back from the insert rather than supplied.
 */
export async function createHouse(name: string, ownerId: string): Promise<House> {
  const trimmed = name.trim();

  const { data: house, error } = await supabase
    .from('houses')
    .insert({ name: trimmed, owner_id: ownerId })
    .select(HOUSE_COLUMNS)
    .single<House>();

  if (error || !house) {
    throw describeCreateError(error, trimmed);
  }

  const { error: membershipError } = await supabase
    .from('memberships')
    .insert({ house_id: house.id, user_id: ownerId });

  if (membershipError) {
    // Compensating delete - the owner has DELETE on their own house.
    await supabase.from('houses').delete().eq('id', house.id);
    throw new Error(
      `Created "${trimmed}" but could not add you to it, so it was undone. Please try again.`
    );
  }

  return house;
}

function describeCreateError(error: PostgrestError | null, name: string): Error {
  if (!isPostgrestError(error)) {
    return new Error('Could not create the house. Please try again.');
  }

  if (error.code === UNIQUE_VIOLATION) {
    // houses.name is unique across the whole app, not just per user.
    return new Error(`A house called "${name}" already exists. Try a different name.`);
  }

  if (error.code === CHECK_VIOLATION) {
    return new Error('That house name is not valid. Give it a real name.');
  }

  return new Error(`Could not create the house. ${error.message}`);
}

/**
 * Join a house by its code, via the `join_house` RPC.
 *
 * It has to be an RPC: RLS cannot express "you may read this house only if you can
 * name its code", so the lookup runs inside a SECURITY DEFINER function that
 * returns only the house it just enrolled you in.
 *
 * Note it is idempotent - re-joining a house you are already in succeeds and
 * returns that house rather than failing.
 */
export async function joinHouse(code: string): Promise<House> {
  const normalised = code.trim().toUpperCase();

  if (!normalised) {
    throw new Error('Enter a join code.');
  }

  const { data, error } = await supabase.rpc('join_house', { code: normalised });

  if (error) {
    if (error.message.includes('no house with that join code')) {
      throw new Error(`No house has the code ${normalised}. Check it and try again.`);
    }
    if (error.message.includes('must be signed in')) {
      throw new Error('Your session expired. Sign in again.');
    }
    throw new Error(`Could not join that house. ${error.message}`);
  }

  // `join_house` returns a single `houses` row - a composite, not a set - so
  // PostgREST sends one object. Without generated database types supabase-js has no
  // way to infer that, hence the cast.
  const house = data as House | null;

  if (!house) {
    throw new Error(`No house has the code ${normalised}. Check it and try again.`);
  }

  return house;
}

/**
 * Leave a house - delete the caller's own membership row.
 *
 * The owner cannot leave their own house: the DELETE policy deliberately
 * excludes the owner's own row. Leaving would strand the house owned by someone
 * no longer in it, since `houses.owner_id` and membership are checked
 * independently everywhere else in RLS, and there is no ownership-transfer
 * feature to hand it off first. (The existing "owners can delete their house"
 * policy - see deleteHouse below - already lets an owner close a house down
 * entirely instead.)
 *
 * A 0-row result is how that refusal actually surfaces: DELETE has no WITH CHECK
 * to violate, so RLS just quietly excludes the row rather than raising an error.
 * This distinguishes that case from a real failure.
 */
export async function leaveHouse(houseId: string, userId: string): Promise<void> {
  const { data, error } = await supabase
    .from('memberships')
    .delete()
    .eq('house_id', houseId)
    .eq('user_id', userId)
    .select();

  if (error) {
    throw new Error(`Could not leave the house. ${error.message}`);
  }
  if (!data || data.length === 0) {
    throw new Error("As the owner, you can't leave this house. You would need to delete it instead.");
  }
}

/**
 * Delete a house entirely - only the owner can (the `houses` DELETE policy is
 * `is_house_owner(id)`, nothing else).
 *
 * Every membership, game, game_player, and buy_in for this house is `ON DELETE
 * CASCADE`'d from the `houses` row, so this one statement removes all of it:
 * every member loses access, every game's history is gone, in the same instant,
 * for everyone, permanently - regardless of whether a game was settled. Verified
 * live against the production project (see ARCHITECTURE.md).
 *
 * A 0-row result means RLS refused it - not the owner, or the house is already
 * gone - the same distinction leaveHouse makes for the same reason.
 */
export async function deleteHouse(houseId: string): Promise<void> {
  const { data, error } = await supabase.from('houses').delete().eq('id', houseId).select();

  if (error) {
    throw new Error(`Could not delete the house. ${error.message}`);
  }
  if (!data || data.length === 0) {
    throw new Error('Could not delete this house. Only the owner can delete a house.');
  }
}
