import { Redirect, useRouter } from 'expo-router';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, TextInput, View } from 'react-native';

import { Button } from '@/components/button';
import { Message } from '@/components/message';
import { ScreenLoader } from '@/components/screen-loader';
import { ThemedText } from '@/components/themed-text';
import { MaxContentWidth, Spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
import { useAuth } from '@/lib/auth';
import { createHouse, type House } from '@/lib/houses';

export default function NewHouseScreen() {
  const theme = useTheme();
  const router = useRouter();
  const { session, isRestoring } = useAuth();

  const [name, setName] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [created, setCreated] = useState<House | null>(null);

  if (isRestoring) {
    return <ScreenLoader />;
  }

  if (!session) {
    return <Redirect href="/sign-in" />;
  }

  const userId = session.user.id;

  async function submit() {
    if (!name.trim()) {
      setError('Give your house a name.');
      return;
    }

    setBusy(true);
    setError(null);

    try {
      // Deliberately does NOT navigate on success. The join code is generated by the
      // database and this is the first and only time it is put in front of the owner,
      // so they get to read it before moving on.
      setCreated(await createHouse(name, userId));
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Could not create the house.');
    } finally {
      setBusy(false);
    }
  }

  if (created) {
    return (
      <ScreenShell>
        <View style={styles.header}>
          <ThemedText type="subtitle">{created.name}</ThemedText>
          <ThemedText type="small" themeColor="textSecondary">
            Your house is ready.
          </ThemedText>
        </View>

        <View style={[styles.codeCard, { backgroundColor: theme.backgroundElement }]}>
          <ThemedText type="small" themeColor="textSecondary">
            Your join code is
          </ThemedText>
          <ThemedText selectable style={styles.code}>
            {created.join_code}
          </ThemedText>
          <ThemedText type="small" themeColor="textSecondary" style={styles.codeHint}>
            Share it with friends so they can join.
          </ThemedText>
        </View>

        <Button label="Done" onPress={() => router.replace('/houses')} />
      </ScreenShell>
    );
  }

  return (
    <ScreenShell>
      <View style={styles.header}>
        <ThemedText type="subtitle">Start a house</ThemedText>
        <ThemedText type="small" themeColor="textSecondary">
          Pick a name your group will recognise. Names are unique across the app.
        </ThemedText>
      </View>

      <View style={styles.form}>
        <View style={styles.field}>
          <ThemedText type="smallBold">House name</ThemedText>
          <TextInput
            value={name}
            onChangeText={setName}
            placeholder="Tuesday Night"
            placeholderTextColor={theme.textSecondary}
            autoCapitalize="words"
            autoCorrect={false}
            editable={!busy}
            maxLength={60}
            returnKeyType="go"
            onSubmitEditing={submit}
            style={[styles.input, { color: theme.text, backgroundColor: theme.backgroundElement }]}
          />
        </View>

        {error ? <Message tone="error">{error}</Message> : null}

        <Button label="Create house" onPress={submit} busy={busy} />
      </View>
    </ScreenShell>
  );
}

function ScreenShell({ children }: { children: React.ReactNode }) {
  return (
    <KeyboardAvoidingView
      style={styles.flex}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
      <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled">
        <View style={styles.content}>{children}</View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  flex: { flex: 1 },
  scroll: { flexGrow: 1, padding: Spacing.four },
  content: {
    width: '100%',
    maxWidth: MaxContentWidth,
    alignSelf: 'center',
    gap: Spacing.five,
  },
  header: { gap: Spacing.two },
  form: { gap: Spacing.three },
  field: { gap: Spacing.two },
  input: {
    minHeight: 48,
    borderRadius: 12,
    paddingHorizontal: Spacing.three,
    fontSize: 16,
  },
  codeCard: {
    alignItems: 'center',
    gap: Spacing.two,
    padding: Spacing.four,
    borderRadius: 12,
  },
  code: {
    fontSize: 40,
    lineHeight: 48,
    fontWeight: '700',
    letterSpacing: 6,
  },
  codeHint: { textAlign: 'center' },
});
